/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.leenjewel.multiplechoice.view;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.leenjewel.multiplechoice.panel.JTabbedPaneWithCloseIcons;
import org.leenjewel.multiplechoice.view.iview.IQuestionView;

/**
 *
 * @author leenjewel
 */
public class AppView extends javax.swing.JFrame {

    /**
     * Creates new form AppView
     */
    public AppView() {
        initComponents();
        initTabs();
    }

    private void setStatusText(String status) {
        jLabelAppViewStatus.setText(status);
    }

    private void initTabs() {
        jTabbedPaneAppViewTabs.addChangeListener(new ChangeListener(){

            @Override
            public void stateChanged(ChangeEvent ce) {
                IQuestionView qview = (IQuestionView)((JTabbedPaneWithCloseIcons)ce.getSource()).getSelectedComponent();
                if (qview == null) {
                    setStatusText("欢迎使用！");
                } else {
                    setStatusText(qview.getQuestionModel().getTitle());
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooserAppView = new javax.swing.JFileChooser();
        jTabbedPaneAppViewTabs = new JTabbedPaneWithCloseIcons();
        jLabelAppViewStatus = new javax.swing.JLabel();
        jMenuBarAppView = new javax.swing.JMenuBar();
        jMenuAppViewFile = new javax.swing.JMenu();
        jMenuItemAppViewOpen = new javax.swing.JMenuItem();
        jMenuItemAppViewQuit = new javax.swing.JMenuItem();
        jMenuAppViewAbout = new javax.swing.JMenu();
        jMenuItemAppViewAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("问卷调查");

        jLabelAppViewStatus.setText("欢迎使用！");

        jMenuAppViewFile.setText("文件");

        jMenuItemAppViewOpen.setText("打开问卷");
        jMenuItemAppViewOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAppViewOpenActionPerformed(evt);
            }
        });
        jMenuAppViewFile.add(jMenuItemAppViewOpen);

        jMenuItemAppViewQuit.setText("退出");
        jMenuItemAppViewQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAppViewQuitActionPerformed(evt);
            }
        });
        jMenuAppViewFile.add(jMenuItemAppViewQuit);

        jMenuBarAppView.add(jMenuAppViewFile);

        jMenuAppViewAbout.setText("关于");

        jMenuItemAppViewAbout.setText("关于本程序");
        jMenuAppViewAbout.add(jMenuItemAppViewAbout);

        jMenuBarAppView.add(jMenuAppViewAbout);

        setJMenuBar(jMenuBarAppView);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jTabbedPaneAppViewTabs, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 835, Short.MAX_VALUE)
                    .add(jLabelAppViewStatus, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jTabbedPaneAppViewTabs, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabelAppViewStatus)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAppViewOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAppViewOpenActionPerformed
        FileNameExtensionFilter fileFilter = new FileNameExtensionFilter("问卷文件","mcdata");
        jFileChooserAppView.addChoosableFileFilter(fileFilter);
        int openId = jFileChooserAppView.showOpenDialog(this);
        if (openId == JFileChooser.APPROVE_OPTION) {
            setStatusText("正在载入问卷......");
            java.awt.EventQueue.invokeLater(new Runnable() {

                @Override
                public void run() {
                    File f = jFileChooserAppView.getSelectedFile();
                    QuestionView qview = new QuestionView(f, AppView.this);
                    jTabbedPaneAppViewTabs.addTab(qview.getQuestionModel().getTitle(), qview);
                    setStatusText(qview.getQuestionModel().getTitle());
                }
            });

        }
    }//GEN-LAST:event_jMenuItemAppViewOpenActionPerformed

    private void jMenuItemAppViewQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAppViewQuitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemAppViewQuitActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooserAppView;
    private javax.swing.JLabel jLabelAppViewStatus;
    private javax.swing.JMenu jMenuAppViewAbout;
    private javax.swing.JMenu jMenuAppViewFile;
    private javax.swing.JMenuBar jMenuBarAppView;
    private javax.swing.JMenuItem jMenuItemAppViewAbout;
    private javax.swing.JMenuItem jMenuItemAppViewOpen;
    private javax.swing.JMenuItem jMenuItemAppViewQuit;
    private JTabbedPaneWithCloseIcons jTabbedPaneAppViewTabs;
    // End of variables declaration//GEN-END:variables
}
